// templates/Web/Pages/React.MasterDetail/src/components/ReactMasterDetail/MasterDetailSideBarTab.jsx
﻿import React from "react";
import classnames from "classnames";
import styles from "./masterdetail.module.css";

export default function MasterDetailSideBarTab({ sampleOrder, selectSampleOrder }) {
  return (
    <button
      onClick={() => selectSampleOrder(sampleOrder)}
      type="button"
      className={classnames(
        "list-group-item",
        "list-group-item-action",
        styles.sidebarText
      )}
    >
      <img src={ sampleOrder.imageSrc !='' ? sampleOrder.imageSrc: '../../../assets/GreyAvatar.svg'} alt="Default Grey Avatar" className="mr-3" />
      {sampleOrder.title}
    </button>
  );
}

// templates/Web/Pages/Angular.MasterDetail/src/app/app-shell/Param_SourceName_Kebab/master-detail-sidebar-tab/master-detail-sidebar-tab.component.ts
﻿import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';
import { ISampleOrder } from '../master-detail.model';

@Component({
  selector: 'app-master-detail-sidebar-tab',
  templateUrl: './master-detail-sidebar-tab.component.html',
  styleUrls: ['./master-detail-sidebar-tab.component.css']
})
export class MasterDetailSidebarTabComponent {
  @Input() sampleOrder: ISampleOrder;
  @Output() itemClick = new EventEmitter<ISampleOrder>();

  selectSampleOrder() {
    this.itemClick.emit();
  }
}

﻿<button
  (click)="selectSampleOrder()"
  type="button"
  class="list-group-item list-group-item-action sidebarText"
>
  <img src="{{ sampleOrder.imageSrc ? sampleOrder.imageSrc : '../../../assets/GreyAvatar.svg' }}" alt="Default Grey Avatar" title="Default Grey Avatar" aria-label="Default Grey Avatar" class="mr-3" />
  {{ sampleOrder.title }}
</button>
