// templates/Web/Pages/Vue.MasterDetail/src/components/MasterDetailSideBarTab.vue
﻿<template>
  <button
    v-on:click="$emit('onDisplayTabClick', index)"
    type="button"
    class="list-group-item list-group-item-action styles.sidebarText"
  >
    <img src="../assets/GreyAvatar.svg" alt="Default Grey Avatar" class="mr-3">
    {{tabText}}
  </button>
</template>

<script>
export default {
  name: "MasterDetailSideBarTab",
  props: {
    tabText: String,
    index: Number
  }
};
</script>

<style scoped>
.sidebarText {
  font-weight: 500;
}
</style>

// src/extension/src/template_test/Flask_ReactJS/Flask_ReactJS/src/components/Master_Detail/MasterDetailSideBarTab.jsx
﻿import React from "react";
import classnames from "classnames";
import styles from "./masterdetail.module.css";

export default function MasterDetailSideBarTab(props) {
  const { index, image, tabText, onDisplayTabClick } = props;
  return (
    <button
      onClick={() => onDisplayTabClick(index)}
      type="button"
      className={classnames(
        "list-group-item",
        "list-group-item-action",
        styles.sidebarText
      )}
    >
      <img src={image} alt="Default Grey Avatar" className="mr-3" />
      {tabText}
    </button>
  );
}
