// templates/Web/Pages/Angular.MasterDetail/frontend/src/app/app-shell/Param_SourceName_Kebab/detail/detail.component.ts
﻿import { Component, OnInit, Input } from '@angular/core';
import { ISampleOrder } from '../Param_SourceName_Kebab.model';

@Component({
  selector: 'app-page',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.css']
})
export class DetailComponent implements OnInit {
  @Input() sampleOrder: ISampleOrder;

  constructor() {}

  ngOnInit(): void {}
}

﻿<div class="row heading">
  <div class="col">
    <h3 class="ml-3 mb-4">{{ sampleOrder.title }}</h3>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-12 ml-3 mb-5 mt-3">
    <p class="title">Status</p>
    <p>{{ sampleOrder.status }}</p>
    <p class="title">Order Date</p>
    <p>{{ sampleOrder.orderDate }}</p>
    <p class="title">Ship To</p>
    <p>{{ sampleOrder.shipTo }}</p>
    <p class="title">Order Total</p>
    <p>{{ sampleOrder.orderTotal }}</p>
    <p class="title">Description</p>
    <p>{{ sampleOrder.longDescription }}</p>
  </div>
</div>

// templates/Web/Pages/React.MasterDetail/frontend/src/components/ReactMasterDetail/Detail.jsx
﻿import React from "react";
import classnames from "classnames";
import styles from "./styles.module.css";
import PropTypes from "prop-types";

const Detail = ({ textSampleData }) => {
  const {
    longDescription,
    title,
    status,
    shipTo,
    orderTotal,
    orderDate
  } = textSampleData;

  return (
    <div className="col">
      <div className={classnames("row", styles.heading)}>
        <div className="col">
          <h3 className="ml-3 mb-4">{title}</h3>
        </div>
      </div>
      <div className="row">
        <div className="col-md-8 col-12 ml-3 mb-5 mt-3">
          <p className={styles.title}>Status</p>
          <p>{status}</p>
          <p className={styles.title}>Order Date</p>
          <p>{orderDate}</p>
          <p className={styles.title}>Ship To</p>
          <p>{shipTo}</p>
          <p className={styles.title}>Order Total</p>
          <p>{orderTotal}</p>
          <p className={styles.title}>Description</p>
          <p>{longDescription}</p>
        </div>
      </div>
    </div>
  );
}

Detail.propTypes = {
  textSampleData: PropTypes.any
}

export default Detail;
