// mocks/react-mocks/src/components/MasterDetail/MasterDetailPage.jsx
import React from "react";
import classnames from "classnames";
import styles from "./masterdetail.module.css";

export default function MasterDetailPage(props) {
  const {
    longDescription,
    title,
    status,
    shipTo,
    orderTotal,
    orderDate
  } = props.textSampleData;
  return (
    <div className="col">
      <div className={classnames("row", styles.heading)}>
        <div className="col">
          <h3 className="ml-3 mb-4">{title}</h3>
        </div>
      </div>
      <div className="row">
        <div className="col-12 mt-3">
          <nav aria-label="breadcrumb">
            <ol className="breadcrumb bg-white mb-0">
              <li className="breadcrumb-item">
                <a className={styles.breadCrumbLink} href="/masterdetail">
                  Master Detail
                </a>
              </li>
              <li className="breadcrumb-item active" aria-current="page">
                {title}
              </li>
            </ol>
          </nav>
        </div>
        <div className="col-md-8 col-12 ml-3 mb-5">
          <p className={styles.title}>Status</p>
          <p>{status}</p>
          <p className={styles.title}>Order Date</p>
          <p>{orderDate}</p>
          <p className={styles.title}>Ship To</p>
          <p>{shipTo}</p>
          <p className={styles.title}>Order Total</p>
          <p>{orderTotal}</p>
          <p className={styles.title}>Description</p>
          <p>{longDescription}</p>
        </div>
      </div>
    </div>
  );
}

// templates/Web/Pages/Angular.MasterDetail/src/app/app-shell/Param_SourceName_Kebab/master-detail-page/master-detail-page.component.ts
﻿import { Component, OnInit, Input } from '@angular/core';
import { IMasterDetailText } from '../master-detail.service';

@Component({
  selector: 'app-master-detail-page',
  templateUrl: './master-detail-page.component.html',
  styleUrls: ['./master-detail.component.css']
})
export class MasterDetailPageComponent implements OnInit {

  @Input() textSampleData: IMasterDetailText;
  constructor() { }

  ngOnInit() {
  }

}


﻿<div class="row heading">
  <div class="col">
    <h3 class="ml-3 mb-4">{{ textSampleData.title }}</h3>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-white mb-0">
        <li class="breadcrumb-item">
          <a class="breadCrumbLink" href="/Param_SourceName_Kebab" title="AngularMasterDetail" aria-label="AngularMasterDetail">
            AngularMasterDetail
          </a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">
          {{ textSampleData.title }}
        </li>
      </ol>
    </nav>
  </div>
  <div class="col-md-8 col-12 ml-3 mb-5">
    <p class="title">Status</p>
    <p>{{ textSampleData.status }}</p>
    <p class="title">Order Date</p>
    <p>{{ textSampleData.orderDate }}</p>
    <p class="title">Ship To</p>
    <p>{{ textSampleData.shipTo }}</p>
    <p class="title">Order Total</p>
    <p>{{ textSampleData.orderTotal }}</p>
    <p class="title">Description</p>
    <p>{{ textSampleData.longDescription }}</p>
  </div>
</div>
