// mockup/Vue3/src/components/Footer.vue
﻿<template>
  <footer class="footer">
    <div class="container-fluid">
      <div class="row justify-content-around">
        <div class="col-8 col-md-5">
          <h5 class="title">myApp77</h5>
          <p class="description">This is placeholder text. Your web app description goes here.</p>
        </div>
        <div class="col-2">
          <ul class="list-unstyled">
            <li>
              <a class="footerlink" href="/">Example Link</a>
            </li>
            <li>
              <a class="footerlink" href="/">Example Link</a>
            </li>
            <li>
              <a class="footerlink" href="/">Example Link</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: "Footer"
};
</script>


<style scoped>
.footer {
  background-color: #1d1d1d;
  padding-top: 2rem;
  padding-bottom: 4rem;
}

.title {
  color: #fff;
}

.description {
  color: #fff;
}

.footerlink,
.footerlink:hover {
  color: #fff;
}
</style>

// mocks/materialui-multi-page/src/components/Footer/index.jsx
import React from "react";
import styles from "./footer.module.css";

export default function Footer() {
  return (
    <footer className={styles.footer}>
      <div className="container-fluid">
        <div className="row justify-content-around">
          <div className="col-8 col-md-5">
            <h5 className={styles.title}>Project Name</h5>
            <p className={styles.description}>
              This is placeholder text. Your web app description goes here.
            </p>
          </div>
          <div className="col-2">
            <ul className="list-unstyled">
              <li>
                <a className={styles.footerlink} href="/">
                  Example Link 1
                </a>
              </li>
              <li>
                <a className={styles.footerlink} href="/">
                  Example Link 2
                </a>
              </li>
              <li>
                <a className={styles.footerlink} href="/">
                  Example Link 3
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  );
}
