// templates/Web/_composition/Vue/Page.Vue.AddWarnings/src/components/WarningMessage.vue
﻿<template>
  <div class="alert alert-warning ml-3 warningPosition" role="alert">
    {{text}}
    <button v-on:click="$emit('onWarningClose')" class="close ml-2" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</template>

<script>
export default {
  name: "WarningMessage",
  props: {
    text: String
  }
};
</script>

<style scoped>
.warningPosition {
  position: fixed !important;
  bottom: 0;
  left: 0;
  z-index: 1030;
}
</style>

// mocks/materialui-multi-page/src/components/WarningMessage/index.jsx
import React from "react";
import classnames from "classnames";
import styles from "./warningmessage.module.css";

// A pop up message used to warn users about failed API calls to the back end
export default function index(props) {
  const { open, text, onWarningClose } = props;
  return (
    <React.Fragment>
      {open && (
        <div
          className={classnames(
            "alert",
            "alert-warning",
            "ml-3",
            styles.warningPosition
          )}
          role="alert"
        >
          {text}
          <button
            onClick={() => onWarningClose()}
            className="close ml-2"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      )}
    </React.Fragment>
  );
}
