// mocks/materialui-multi-page/src/components/NavBar/index.jsx
import React from "react";

//TODO Project Acorn: Add a new link in the NavBar for your page here.
export default function NavBar() {
  return (
    <nav className="navbar navbar-expand-sm navbar-light border-bottom justify-content-between">
      <a className="navbar-brand" href="/">
        Project Name
      </a>
      <div className="navbar-nav">
        <a className="nav-item nav-link active" href="/masterdetail">
          Master Detail
        </a>
        <a className="nav-item nav-link active" href="/grid">
          Content Grid
        </a>
        <a className="nav-item nav-link active" href="/list">
          List
        </a>
        <a className="nav-item nav-link active" href="/blank">
          Blank
        </a>
      </div>
    </nav>
  );
}

// src/extension/src/template_test/Flask_Angular/Flask_Angular/src/app/app-shell/nav-bar/nav-bar.component.ts
﻿import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {
  skipLinkPath: string;
  constructor(private location: Location) { }

  ngOnInit() {
    this.skipLinkPath = `${this.location.path()}#mainContent`;
  }
}

﻿<div class="skipLink">
  <a [href]="skipLinkPath">Skip to Main Content</a>
</div>
<nav
  class="navbar navbar-expand-sm navbar-light border-bottom justify-content-between"
>
  <a class="navbar-brand" routerLink="/">
    Flask_Angular
  </a>
  <div class="navbar-nav">
    <a class="nav-item nav-link active" routerLink="/blank">
      Blank
    </a>
    <a class="nav-item nav-link active" routerLink="/grid">
      Grid
    </a>
    <a class="nav-item nav-link active" routerLink="/list">
      List
    </a>
    <a class="nav-item nav-link active" routerLink="/master-detail">
      Master_Detail
    </a>
  </div>
</nav>
