// templates/Web/Pages/React.List/src/components/ReactList/ListForm.jsx
﻿import React from "react";

export default function ListForm(props) {
  const { onAddListItem, textField, onChangeInputText } = props;
  return (
    <div className="input-group my-3">
      <input
        type="text"
        onChange={event => onChangeInputText(event, "textField")}
        value={textField}
        className="form-control"
        placeholder="Add text here..."
        aria-label="Add text here..."
      />
      <button className="btn btn-primary ml-2" onClick={onAddListItem}>
        Submit
      </button>
    </div>
  );
}

// templates/Web/Pages/Vue.List/src/components/ListForm.vue
﻿<template>
  <form class="input-group my-3" v-on:submit="$emit('onAddListItem')">
    <input
      v-bind:value="value"
      v-on:input="$emit('input', $event.target.value)"
      type="text"
      class="form-control"
      placeholder="Add text here..."
      aria-label="Add text here..."
    >
    <button type="submit" class="btn btn-primary ml-2">Submit</button>
  </form>
</template>

<script>
export default {
  name: "ListForm",
  props: {
    value: String
  }
};
</script>
