// templates/Web/Pages/React.List/src/components/ReactList/ListItem.jsx
﻿import React from "react";

export default function ListItem(props) {
  const { listItem, onDeleteListItem } = props;
  return (
    <div className="col-12 mb-3 border">
      <div className="row">
        <div className="col-11">
          <p className="mt-3">{listItem.text}</p>
        </div>
        <div className="col-1">
          <button
            type="button"
            className="close py-2"
            data-dismiss="alert"
            aria-label="Close"
            onClick={() => onDeleteListItem(listItem)}
          >
            <div aria-hidden="true">&times;</div>
          </button>
        </div>
      </div>
    </div>
  );
}

// templates/Web/Pages/Vue.List/src/components/ListItem.vue
﻿<template>
  <div class="col-12 mb-3 border">
    <div class="row">
      <div class="col-11">
        <p class="mt-3">{{listItem.text}}</p>
      </div>
      <div class="col-1">
        <button
          type="button"
          class="close py-2"
          data-dismiss="alert"
          aria-label="Close"
          @click="$emit('onDeleteListItem', listItem)"
        >
          <div aria-hidden="true">&times;</div>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ListItem",
  props: {
    listItem: Object
  }
};
</script>
