// templates/Web/Pages/React.MasterDetail/src/components/ReactMasterDetail/MasterDetailSideBarTab.jsx
﻿import React from "react";
import classnames from "classnames";
import styles from "./masterdetail.module.css";

export default function MasterDetailSideBarTab({ sampleOrder, selectSampleOrder }) {
  return (
    <button
      onClick={() => selectSampleOrder(sampleOrder)}
      type="button"
      className={classnames(
        "list-group-item",
        "list-group-item-action",
        styles.sidebarText
      )}
    >
      <img src={ sampleOrder.imageSrc !='' ? sampleOrder.imageSrc: '../../../assets/GreyAvatar.svg'} alt="Default Grey Avatar" className="mr-3" />
      {sampleOrder.title}
    </button>
  );
}

// templates/Web/Pages/Vue.MasterDetail/src/components/MasterDetailSideBarTab.vue
﻿<template>
  <button
    class="list-group-item list-group-item-action styles.sidebarText"
    type="button"
    @click="$emit('selectSampleOrder', sampleOrder)"
  >
    <img class="mr-3" :src="sampleOrder.imageSrc ? sampleOrder.imageSrc : imgGreyAvatar" alt="Default Grey Avatar" />
    {{sampleOrder.title}}
  </button>
</template>

<script>
import imgGreyAvatar from '../assets/GreyAvatar.svg';
export default {
  name: "MasterDetailSideBarTab",
  props: {
    sampleOrder: {
      type: Object,
      required: true
    }
  },
  data (){
    return {
      imgGreyAvatar
    }
  }
};
</script>

<style scoped>
.sidebarText {
  font-weight: 500;
}
</style>
