// src/extension/src/template_test/NodeJS_Vue/NodeJS_Vue/src/components/GridComponent.vue
﻿<template>
  <div class="col-md-4 col-sm-12 p-5">
    <img src="../assets/GreyBox.svg" alt="Default Grey Box" class="mb-3">
    <h3>{{header}}</h3>
    <p>{{description}}</p>
  </div>
</template>

<script>
export default {
  name: "GridComponent",
  props: {
    header: String,
    description: String
  }
};
</script>

// mocks/materialui-multi-page/src/components/Grid/GridComponent.jsx
import React from "react";

export default function GridComponent(props) {
  const { image, header, description } = props;
  return (
    <div className="col-md-4 col-sm-12 p-5">
      <img src={image} alt="Default Grey Box" className="mb-3" />
      <h3>{header}</h3>
      <p>{description}</p>
    </div>
  );
}
