// templates/Web/Pages/React.MasterDetail/frontend/src/components/Param_SourceName_Pascal/MasterList.js
﻿import React from "react";
import classnames from "classnames";
import styles from "./styles.module.css";
import imgGreyAvatar from "../../images/GreyAvatar.svg";
import PropTypes from "prop-types";

const MasterList = ({ sampleOrder, selectSampleOrder, isActive }) => {
  return (
    <button
      onClick={() => selectSampleOrder(sampleOrder)}
      type="button"
      className={classnames(
        "list-group-item",
        "list-group-item-action",
        styles.sidebarText,
        { "active": isActive }
      )}
    >
      <img src={ sampleOrder.imageSrc ? sampleOrder.imageSrc : imgGreyAvatar} alt={sampleOrder.title} className="mr-3" />
      {sampleOrder.title}
    </button>
  );
}

MasterList.propTypes = {
  sampleOrder: PropTypes.any,
  selectSampleOrder: PropTypes.func,
  isActive: PropTypes.bool
}

export default MasterList;

// templates/Web/Pages/Angular.MasterDetail/frontend/src/app/app-shell/Param_SourceName_Kebab/master-list/master-list.component.ts
﻿import { Component, OnInit, Output, EventEmitter, Input } from '@angular/core';
import { ISampleOrder } from '../Param_SourceName_Kebab.model';

@Component({
  selector: 'app-master-list',
  templateUrl: './master-list.component.html',
  styleUrls: ['./master-list.component.css']
})
export class MasterListComponent implements OnInit {
  @Input() sampleOrder: ISampleOrder;
  @Input() isActive: boolean;
  @Output() itemClick = new EventEmitter<ISampleOrder>();

  constructor() {}

  ngOnInit(): void {}

  selectSampleOrder(): void {
    this.itemClick.emit();
  }
}

﻿<button
  (click)="selectSampleOrder()"
  type="button"
  class="list-group-item list-group-item-action sidebarText"
  [ngClass]="{'active' : isActive}"
>
  <img src="{{ sampleOrder.imageSrc ? sampleOrder.imageSrc : '../../../assets/GreyAvatar.svg' }}" alt="{{ sampleOrder.title }}" class="mr-3" />
  {{ sampleOrder.title }}
</button>
