// mockup/Vue3/src/components/GridComponent.vue
﻿<template>
  <b-col sm="12" md="4" class="p-5">
    <img class="mb-3" src="@/assets/GreyBox.svg" alt="Default Grey Box" />
    <h3>{{header}}</h3>
    <p>{{description}}</p>
  </b-col>
</template>

<script>
export default {
  name: "GridComponent",
  props: {
    header: {
      type: String,
      required: true
    },
    description: {
      type: String,
      required: true
    }
  }
};
</script>

// templates/Web/Pages/React.Grid/src/components/ReactGrid/GridComponent.jsx
﻿import React from "react";

export default function GridComponent({ griItem }) {
  return (
    <div className="col-md-4 col-sm-12 p-5">
      <img src="@/assets/GreyBox.svg" alt="Default Grey Box" className="mb-3" />
      <h3>{griItem.header}</h3>
      <p>{griItem.shortDescription}</p>
    </div>
  );
}
