// templates/Web/Pages/Angular.Grid/src/app/app-shell/AngularGrid/grid.component.ts
﻿import { Component, OnInit } from '@angular/core';
import { CONSTANTS } from '../../../constants';
import { IGridTextItem } from './GridBox/grid-box.component';
import { GridService } from './grid.service';

@Component({
  selector: 'app-grid',
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.css']
})
export class GridComponent implements OnInit {

  GreyBox = require('../../images/GreyBox.svg') as string;
  WarningMessageText = CONSTANTS.ERROR_MESSAGE.GRID_GET;
  WarningMessageOpen = false;
  gridTextAssets: IGridTextItem[] = [
    {
      description: 'example1',
      header: 'example1',
      id: 0
    },
    {
      description: 'example2',
      header: 'example2',
      id: 1
    }
  ];
  constructor(private gridService: GridService) { }

  ngOnInit() {
    this.gridService.getGridItems().subscribe(
      result => {
        this.gridTextAssets = result;
      },
      error => {
        this.WarningMessageOpen = true;
        this.WarningMessageText = `${CONSTANTS.ERROR_MESSAGE.GRID_GET} ${error}`;
      }
    );
  }
  handleWarningClose(open: boolean) {
    this.WarningMessageOpen = open;
    this.WarningMessageText = '';
  }
}

﻿<main id="mainContent">
  <div class="text-center header">
    <h1>Param_ProjectName</h1>
    <p>This is placeholder text. Your web app description goes here.</p>
    <a
      href="https://github.com/Microsoft/WebTemplateStudio"
      class="btn btn-primary my-2"
    >
      Link to our Github
    </a>
  </div>

  <div class="container">
    <div class="row justify-content-center py-5">
      <h1>Bootstrap AngularGrid Template</h1>
    </div>
    <div class="row justify-content-around text-center pb-5">
      <app-grid-box
        class="col-4 p-5"
        *ngFor="let textAssets of gridTextAssets"
        [key]="textAssets.id"
        [header]="textAssets.title"
        [description]="textAssets.shortDescription"
      >
      </app-grid-box>
    </div>
  </div>
  <app-warning-message
    *ngIf="WarningMessageOpen"
    [text]="WarningMessageText"
    (WarningMessageOpenEventEmitter)="handleWarningClose($event)"
  >
  </app-warning-message>
</main>

// src/extension/src/template_test/Flask_Angular/Flask_Angular/src/components/Grid/index.jsx
﻿import React, { Component } from "react";
import classnames from "classnames";
import GridComponent from "./GridComponent";
import WarningMessage from "../WarningMessage";
import GreyBox from "../../images/GreyBox.svg";
import styles from "./grid.module.css";
import CONSTANTS from "../../constants";

export default class Grid extends Component {
  constructor(props) {
    super(props);
    this.state = {
      gridTextAssets: [{ description: "", header: "", id: 0 }],
      WarningMessageOpen: false,
      WarningMessageText: ""
    };

    this.handleWarningClose = this.handleWarningClose.bind(this);
  }

  // Get the text sample data from the back end
  componentDidMount() {
    fetch(CONSTANTS.ENDPOINT.GRID)
      .then(response => {
        if (!response.ok) {
          throw Error(response.statusText);
        }
        return response.json();
      })
      .then(result => this.setState({ gridTextAssets: result }))
      .catch(error =>
        this.setState({
          WarningMessageOpen: true,
          WarningMessageText: `${CONSTANTS.ERROR_MESSAGE.GRID_GET} ${error}`
        })
      );
  }

  handleWarningClose() {
    this.setState({
      WarningMessageOpen: false,
      WarningMessageText: ""
    });
  }

  render() {
    const {
      gridTextAssets,
      WarningMessageOpen,
      WarningMessageText
    } = this.state;
    return (
      <main id="mainContent">
        <div className={classnames("text-center", styles.header)}>
          <h1>Flask-Angular</h1>
          <p>This is placeholder text. Your web app description goes here.</p>
          <a
            href="https://github.com/Microsoft/WebTemplateStudio"
            className="btn btn-primary my-2"
          >
            Link to our Github
          </a>
        </div>

        <div className="container">
          <div className="row justify-content-center py-5">
            <h1>Bootstrap Grid Template</h1>
          </div>

          <div className="row justify-content-around text-center pb-5">
            {gridTextAssets.map(textAssets => (
              <GridComponent
                key={textAssets.id}
                header={textAssets.title}
                description={textAssets.shortDescription}
                image={GreyBox}
              />
            ))}
          </div>
        </div>
        <WarningMessage
          open={WarningMessageOpen}
          text={WarningMessageText}
          onWarningClose={this.handleWarningClose}
        />
      </main>
    );
  }
}
