// mockup/Vue3/src/components/NavBar.vue
﻿//TODO Web Template Studio: Add a new link in the NavBar for your page here.
// A skip link is included as an accesibility best practice. For more information visit https://www.w3.org/WAI/WCAG21/Techniques/general/G1.
<template>
  <div>
    <div class="skipLink">
      <a href="#mainContent">Skip to Main Content</a>
    </div>
    <div class="navbar navbar-expand-sm navbar-light border-bottom justify-content-between">
      <a class="navbar-brand" href="/" role="heading" aria-level="1">myApp85</a>
      <b-nav class="navbar-nav">
        <b-nav-item class="nav-item nav-link active" to="/">Blank</b-nav-item>
        <b-nav-item class="nav-item nav-link active" to="/Grid">Grid</b-nav-item>
        <b-nav-item class="nav-item nav-link active" to="/List">List</b-nav-item>
        <b-nav-item class="nav-item nav-link active" to="/Master_Detail">Master_Detail</b-nav-item>
      </b-nav>
    </div>
  </div>
</template>

<script>
export default {
  name: "NavBar"
};
</script>

<style scoped>
.skipLink a {
  position: absolute;
  left: -100px;
  top: -100px;
}

.skipLink a:focus {
  position: fixed;
  z-index: 1000;
  top: 0;
  left: 0;
  padding: 10px;
  color: #ffffff;
  background: #000000;
}
</style>

// src/extension/src/template_test/NodeJS_ReactJS/NodeJS_ReactJS/src/components/NavBar/index.jsx
﻿import React from "react";
import styles from "./navbar.module.css";

//TODO Web Template Studio: Add a new link in the NavBar for your page here.
// A skip link is included as an accessibility best practice. For more information visit https://www.w3.org/WAI/WCAG21/Techniques/general/G1.
export default function NavBar() {
  return (
    <React.Fragment>
      <div className={styles.skipLink}>
        <a href="#mainContent">Skip to Main Content</a>
      </div>
      <nav className="navbar navbar-expand-sm navbar-light border-bottom justify-content-between">
        <a className="navbar-brand" href="/">
          NodeJS_ReactJS
        </a>
        <div className="navbar-nav">
          <a className="nav-item nav-link active" href="Blank">
            Blank
          </a>
          <a className="nav-item nav-link active" href="Grid">
            Grid
          </a>
          <a className="nav-item nav-link active" href="List">
            List
          </a>
          <a className="nav-item nav-link active" href="Master_Detail">
            Master_Detail
          </a>
        </div>
      </nav>
    </React.Fragment>
  );
}
