// templates/Web/Pages/Vue.List/frontend/src/components/ListItem.vue
﻿<template>
  <div class="col-12 mb-3 border">
    <div class="row">
      <div class="col-11">
        <p class="mt-3">{{listItem.text}}</p>
      </div>
      <div class="col-1">
        <button
          aria-label="delete"
          class="close py-2"
          data-dismiss="alert"
          type="button"
          alt="delete"
          @click="$emit('delete-list-item', listItem)"
        >
          <div aria-hidden="true">&times;</div>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ListItem",
  props: {
    listItem: {
      type: Object,
      required: true,
      validator: function(value) {
        return value.text !== undefined && value.id !== undefined;
      }
    }
  }
};
</script>

// templates/Web/Pages/React.List/src/components/ReactList/ListItem.jsx
﻿import React from "react";
import PropTypes from "prop-types";

const ListItem = ({ item, deleteItem }) => {
  return (
    <div className="col-12 mb-3 border">
      <div className="row">
        <div className="col-11">
          <p className="mt-3">{item.text}</p>
        </div>
        <div className="col-1">
          <button
            type="button"
            className="close py-2"
            data-dismiss="alert"
            aria-label="delete"
            alt={item.text}
            onClick={() => deleteItem(item)}
          >
            <div aria-hidden="true">&times;</div>
          </button>
        </div>
      </div>
    </div>
  );
}

ListItem.propTypes = {
  item: PropTypes.any,
  deleteItem: PropTypes.func
}

export default ListItem;
