// src/extension/src/template_test/Flask_Vue/Flask_Vue/src/components/Grid/index.jsx
﻿import React, { Component } from "react";
import classnames from "classnames";
import GridComponent from "./GridComponent";
import WarningMessage from "../WarningMessage";
import GreyBox from "../../images/GreyBox.svg";
import styles from "./grid.module.css";
import CONSTANTS from "../../constants";

export default class Grid extends Component {
  constructor(props) {
    super(props);
    this.state = {
      gridTextAssets: [{ description: "", header: "", id: 0 }],
      WarningMessageOpen: false,
      WarningMessageText: ""
    };

    this.handleWarningClose = this.handleWarningClose.bind(this);
  }

  // Get the text sample data from the back end
  componentDidMount() {
    fetch(CONSTANTS.ENDPOINT.GRID)
      .then(response => {
        if (!response.ok) {
          throw Error(response.statusText);
        }
        return response.json();
      })
      .then(result => this.setState({ gridTextAssets: result }))
      .catch(error =>
        this.setState({
          WarningMessageOpen: true,
          WarningMessageText: `${CONSTANTS.ERROR_MESSAGE.GRID_GET} ${error}`
        })
      );
  }

  handleWarningClose() {
    this.setState({
      WarningMessageOpen: false,
      WarningMessageText: ""
    });
  }

  render() {
    const {
      gridTextAssets,
      WarningMessageOpen,
      WarningMessageText
    } = this.state;
    return (
      <main id="mainContent">
        <div className={classnames("text-center", styles.header)}>
          <h1>Flask-Vue</h1>
          <p>This is placeholder text. Your web app description goes here.</p>
          <a
            href="https://github.com/Microsoft/WebTemplateStudio"
            className="btn btn-primary my-2"
          >
            Link to our Github
          </a>
        </div>

        <div className="container">
          <div className="row justify-content-center py-5">
            <h1>Bootstrap Grid Template</h1>
          </div>

          <div className="row justify-content-around text-center pb-5">
            {gridTextAssets.map(textAssets => (
              <GridComponent
                key={textAssets.id}
                header={textAssets.title}
                description={textAssets.shortDescription}
                image={GreyBox}
              />
            ))}
          </div>
        </div>
        <WarningMessage
          open={WarningMessageOpen}
          text={WarningMessageText}
          onWarningClose={this.handleWarningClose}
        />
      </main>
    );
  }
}

// src/extension/src/template_test/Flask_Vue/Flask_Vue/src/views/Grid.vue
﻿<template>
  <div>
    <main id="mainContent">
      <div class="text-center header">
        <h1>Flask-Vue</h1>
        <p>This is placeholder text. Your web app description goes here.</p>
        <a
          href="https://github.com/Microsoft/WebTemplateStudio"
          class="btn btn-primary my-2"
        >Link to our Github</a>
      </div>

      <div class="container">
        <div class="row justify-content-center py-5">
          <h1>Bootstrap Grid Template</h1>
        </div>

        <div class="row justify-content-around text-center pb-5">
          <GridComponent
            v-for="textAsset in gridTextAssets"
            v-bind:key="textAsset.id"
            v-bind:header="textAsset.title"
            v-bind:description="textAsset.shortDescription"
          />
        </div>
      </div>
    </main>
    <WarningMessage
      v-if="WarningMessageOpen"
      v-on:onWarningClose="handleWarningClose"
      v-bind:text="WarningMessageText"
    />
  </div>
</template>

<script>
import CONSTANTS from "../constants";
import GridComponent from "../components/GridComponent";
import WarningMessage from "../components/WarningMessage";

export default {
  name: "Grid",

  components: {
    GridComponent,
    WarningMessage
  },

  data: function() {
    return {
      gridTextAssets: [
        {
          description: "",
          header: "",
          id: 0
        }
      ],
      WarningMessageOpen: false,
      WarningMessageText: ""
    };
  },

  created: function() {
    this.fetchTextAssets();
  },

  methods: {
    fetchTextAssets: function() {
      fetch(CONSTANTS.ENDPOINT.GRID)
        .then(response => {
          if (!response.ok) {
            throw Error(response.statusText);
          }
          return response.json();
        })
        .then(result => {
          this.gridTextAssets = result;
        })
        .catch(error => {
          this.WarningMessageOpen = true;
          this.WarningMessageText = `${
            CONSTANTS.ERROR_MESSAGE.GRID_GET
          } ${error}`;
        });
    },
    handleWarningClose: function() {
      this.WarningMessageOpen = false;
      this.WarningMessageText = "";
    }
  }
};
</script>

<style scoped>
.header {
  background-color: #cecece;
  padding-top: 7rem;
  padding-bottom: 7rem;
}
</style>
